MyShop/MyShop.WeUI/Controllers/ProductManagerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyShop.Core.Contracts;
using MyShop.Core.Models;
using MyShop.Core.ViewModels;

namespace MyShop.WeUI.Controllers
{
	[Authorize(Roles = "Admin")]
	public class ProductManagerController : Controller
	{
		IRepository<Product> context;
		IRepository<ProductCategory> productCategories;

		public ProductManagerController(IRepository<Product> productContext, IRepository<ProductCategory> productCategoryContext) {
			context = productContext;
			productCategories = productCategoryContext;
		}
		// GET: ProductManager
		public ActionResult Index()
		{
			List<Product> products = context.Collection().ToList();
			return View(products);
		}

		public ActionResult Create() {
			ProductManagerViewModel viewModel = new ProductManagerViewModel();
			viewModel.Product = new Product();
			viewModel.ProductCategories = productCategories.Collection();
			return View(viewModel);
		}

		[HttpPost]
		public ActionResult Create(Product product, HttpPostedFileBase file) {
			if (!ModelState.IsValid)
			{
				return View(product);
			}
			else {
				if (file != null)
				{
					product.Image = product.Id + Path.GetExtension(file.FileName);
					file.SaveAs(Server.MapPath("//Content//ProductImages//") + product.Image);
				}

				context.Insert(product);
				context.Commit();

				return RedirectToAction("Index");
			}
		}

		public ActionResult Edit(string Id) {
			Product product = context.Find(Id);
			if (product == null)
			{
				return HttpNotFound();
			}
			else {
				ProductManagerViewModel viewModel = new ProductManagerViewModel();
				viewModel.Product = product;
				viewModel.ProductCategories = productCategories.Collection();

				return View(viewModel);
			}
		}
		[HttpPost]
		public ActionResult Edit(Product product, string Id, HttpPostedFileBase file) {
			Product productToEdit = context.Find(Id);
			if (productToEdit == null)
			{
				return HttpNotFound();
			}
			else
			{
				if (!ModelState.IsValid)
				{
					return View(product);
				}
				if (file != null) {
					productToEdit.Image = product.Id + Path.GetExtension(file.FileName);
					file.SaveAs(Server.MapPath("//Content//ProductImages//") + productToEdit.Image);
				}
					productToEdit.Category = product.Category;
					productToEdit.Description = product.Description;
					productToEdit.Name = product.Name;
					productToEdit.Price = product.Price;

					context.Commit();

					return RedirectToAction("Index");
			}
		}
		public ActionResult Delete(string Id) {
			Product productToDelete = context.Find(Id);
			if (productToDelete == null)
			{
				return HttpNotFound();

			}
			else {
				return View(productToDelete);
			}
		}
		[HttpPost]
		[ActionName("Delete")]
		public ActionResult ConfirmDelete(string Id) {
			Product productToDelete = context.Find(Id);
			if (productToDelete == null)
			{
				return HttpNotFound();

			}
			else
			{
				context.Delete(Id);
				context.Commit();
				return RedirectToAction("Index");
			}
		}
    }
}

MyShop/MyShop.WeUI/Views/ProductManager/Create.cshtml
@model MyShop.Core.ViewModels.ProductManagerViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "productManager", FormMethod.Post, new { enctype = "multipart/formdata" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Product.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
				@Html.DropDownListFor(model => model.Product.Category, new SelectList(Model.ProductCategories, "Category", "Category"), new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product.Image, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				<input type="file" class="custom-file-input form-control" data-icon="false">
			</div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyShop/MyShop.WeUI/Views/ProductManager/Delete.cshtml
@model MyShop.Core.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyShop/MyShop.WeUI/Views/ProductManager/Edit.cshtml
@model MyShop.Core.ViewModels.ProductManagerViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "ProductManager", FormMethod.Post, new { encType = "multipart/form-data" }))
{
    @Html.AntiForgeryToken() 
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Product.Id)
		
		<div class="col-md-2">
			<img src="~/Content/ProductImages/@Model.Product.Image" class="img-responsive" />
		</div>
		<div class="col-md-10">
			<div class="form-group">
				@Html.LabelFor(model => model.Product.Name, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Product.Name, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Product.Name, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Product.Description, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Product.Description, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Product.Description, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Product.Price, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Product.Price, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Product.Price, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Product.Category, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.DropDownListFor(model => model.Product.Category, new SelectList(Model.ProductCategories, "Category", "Category"), new { htmlAttributes = new { @class = "form-control" } })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Product.Image, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					<input type="file" name="file" value="" id="file" class="form-control" />
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<input type="submit" value="Save" class="btn btn-default" />
				</div>
			</div>
		</div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyShop/MyShop.WeUI/Views/ProductManager/Index.cshtml
@model IEnumerable<MyShop.Core.Models.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
		<th>
			@Html.DisplayNameFor(model => model.Image)
		</th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
		<th></th>
    </tr>

@foreach (var item in Model) {
<tr>
	<td>
		<img class="img-thumbnail" style="height:50px" src="~/Content/ProductImages/@item.Image" />
	</td>
	<td>
		@Html.DisplayFor(modelItem => item.Name)
	</td>
	<td>
		@Html.DisplayFor(modelItem => item.Description)
	</td>
	<td>
		@Html.DisplayFor(modelItem => item.Price)
	</td>
	<td>
		@Html.DisplayFor(modelItem => item.Category)
	</td>
	<td>
		@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
		@Html.ActionLink("Delete", "Delete", new { id = item.Id })
	</td>
</tr>
}

</table>