MyShop/MyShop.WeUI/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyShop.Contracts;
using MyShop.Core.Contracts;
using MyShop.Core.Models;
using MyShop.Services;

namespace MyShop.WeUI.Controllers
{

	public class BasketController : Controller
	{
		IEBasketService basketService;
		IOrderService orderService;
		IRepository<Customer> customers;

		public BasketController(IEBasketService BasketService, IOrderService OrderService, IRepository<Customer> Customers) {
			basketService = BasketService;
			orderService = OrderService;
			customers = Customers;
		}
		// GET: Basket
		public ActionResult Index()
		{
			var model = basketService.GetBasketItems(HttpContext);
			return View(model);
		}

		public ActionResult AddToBasket(string Id) 
		{
			basketService.AddToBasket(HttpContext, Id);
			return RedirectToAction("Index");
		}

		public ActionResult RemoveFromBasket(string Id)
		{
			basketService.RemoveFromBasket(this.HttpContext, Id);

			return RedirectToAction("Index");
		}

		public PartialViewResult BasketSummary() {
			var basketSummary = basketService.GetBasketSummary(this.HttpContext);

			return PartialView(basketSummary);
		}
		[Authorize]
		public ActionResult Checkout() {
			Customer customer = customers.Collection().FirstOrDefault(c => c.Email == User.Identity.Name);

			if (customer == null)
			{
				Order order = new Order()
				{
					Email = customer.Email,
					City = customer.City,
					State = customer.State,
					Street = customer.Street,
					FirstName = customer.FirstName,
					Surname = customer.LastName,
					ZipCode = customer.ZipCode

				};
				return View(order);
			}
			else
			{
				return RedirectToAction("Error");
			}
		}

		[HttpPost]
		[Authorize]
		public ActionResult Checkout(Order order) {
			var basketItems = basketService.GetBasketItems(this.HttpContext);
			order.OrderStatus = "Order Created";
			order.Email = User.Identity.Name;

			//Process Payment

			order.OrderStatus = "Payment Proccesed";
			orderService.CreateOrder(order, basketItems);
			basketService.ClearBasket(this.HttpContext);

			return RedirectToAction("Thankyou", new { OrderId = order.Id });
		}

		public ActionResult Thankyou(string OrderId) {
			ViewBag.OrderId = OrderId;
			return View();
		}
	}
}

MyShop/MyShop.WeUI/Views/Basket/BasketSummary.cshtml
@model MyShop.Core.ViewModels.BasketSummaryViewModel

<ul class="nav navbar-nav navbar-right">
	<li><a href="@Url.Action("Index", "Basket")">@Model.BasketCount items</a></li>
	<li><a href="@Url.Action("Index", "Basket")">@String.Format("{0:c}", Model.BasketTotal)</a></li>
</ul>

MyShop/MyShop.WeUI/Views/Basket/Checkout.cshtml
@model MyShop.Core.Models.Order

@{
    ViewBag.Title = "Checkout";
}

<h2>Checkout</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Procced To Payment" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyShop/MyShop.WeUI/Views/Basket/Index.cshtml
@model IEnumerable<MyShop.Core.ViewModels.BasketItemViewModel>

@{
	ViewBag.Title = "Basket";
}

<h2>Basket</h2>
<table class="table">
	<tr>
		<th></th>
		<th>
			@Html.DisplayNameFor(model => model.ProductName)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Quanity)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Price)
		</th>
		<th>
			Line Total
		</th>
		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td><img src="~/Content/ProductImages/@item.Image" class="img" style="width:100px;" /></td>
			<td>
				@Html.DisplayFor(modelItem => item.ProductName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Quanity)
			</td>
			<td>
				@String.Format("{0:c}", item.Price)
			</td>
			<td>
				@String.Format("{0:c}", item.Price * item.Quanity)
			</td>
			<td>
				<a href="@Url.Action("RemoveFromBasket", "Basket", new { Id=item.Id })" class="btn btn-danger">Delete</a>
			</td>
		</tr>

	}
	<tr>
		<td colspan="4" style="text-align:right"><strong>Basket Total</strong></td>
		<td>@String.Format("{0:c}", (from p in Model select p.Price * p.Quanity).Sum())</td>
		<td><a href="@Url.Action("Checkout", "Basket")">CheckOut</a></td>
	</tr>

</table>

MyShop/MyShop.WeUI/Views/Basket/RemoveFromBasket.cshtml
@model MyShop.Core.Models.BasketItem

@{
    ViewBag.Title = "RemoveFromBasket";
}

<h2>Your Item Has Been Removed,Back?</h2>
 @Html.ActionLink("Back to List", "Index")

MyShop/MyShop.WeUI/Views/Basket/Thankyou.cshtml
@{
    ViewBag.Title = "Thank you";
}

<h2>Thank you</h2>
Thank you for order.<br /><br />
Your Order Id = @ViewBag.OrderId 